// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace WebApplication2.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class InventoryState
    {
        /// <summary>
        /// Initializes a new instance of the InventoryState class.
        /// </summary>
        public InventoryState() { }

        /// <summary>
        /// Initializes a new instance of the InventoryState class.
        /// </summary>
        public InventoryState(int? orderId = default(int?), string inventoryStateProperty = default(string))
        {
            OrderId = orderId;
            InventoryStateProperty = inventoryStateProperty;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "orderId")]
        public int? OrderId { get; set; }

        /// <summary>
        /// Possible values include: 'PENDING', 'COMPLETED'
        /// </summary>
        [JsonProperty(PropertyName = "inventoryState")]
        public string InventoryStateProperty { get; set; }

    }
}
