// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace WebApplication2.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class InvoiceRequest
    {
        /// <summary>
        /// Initializes a new instance of the InvoiceRequest class.
        /// </summary>
        public InvoiceRequest() { }

        /// <summary>
        /// Initializes a new instance of the InvoiceRequest class.
        /// </summary>
        public InvoiceRequest(int? orderId = default(int?), int? price = default(int?), string customerName = default(string), string customerAddress = default(string))
        {
            OrderId = orderId;
            Price = price;
            CustomerName = customerName;
            CustomerAddress = customerAddress;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "orderId")]
        public int? OrderId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "price")]
        public int? Price { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "customerName")]
        public string CustomerName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "customerAddress")]
        public string CustomerAddress { get; set; }

    }
}
