// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace WebApplication2.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Order
    {
        /// <summary>
        /// Initializes a new instance of the Order class.
        /// </summary>
        public Order() { }

        /// <summary>
        /// Initializes a new instance of the Order class.
        /// </summary>
        public Order(int? orderID = default(int?), int? orderWeight = default(int?), int? orderSize = default(int?), int? articleID = default(int?), int? quantity = default(int?), string customerName = default(string), string customerAddress = default(string), string customerEMail = default(string), int? price = default(int?))
        {
            OrderID = orderID;
            OrderWeight = orderWeight;
            OrderSize = orderSize;
            ArticleID = articleID;
            Quantity = quantity;
            CustomerName = customerName;
            CustomerAddress = customerAddress;
            CustomerEMail = customerEMail;
            Price = price;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "orderID")]
        public int? OrderID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "orderWeight")]
        public int? OrderWeight { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "orderSize")]
        public int? OrderSize { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "articleID")]
        public int? ArticleID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "quantity")]
        public int? Quantity { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "customerName")]
        public string CustomerName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "customerAddress")]
        public string CustomerAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "customerEMail")]
        public string CustomerEMail { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "price")]
        public int? Price { get; set; }

    }
}
