// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace WebApplication2.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ShipmentRequest
    {
        /// <summary>
        /// Initializes a new instance of the ShipmentRequest class.
        /// </summary>
        public ShipmentRequest() { }

        /// <summary>
        /// Initializes a new instance of the ShipmentRequest class.
        /// </summary>
        public ShipmentRequest(int? orderID = default(int?), int? orderSize = default(int?), int? orderWeight = default(int?), string customerName = default(string), string customerAddress = default(string), string customerEmail = default(string))
        {
            OrderID = orderID;
            OrderSize = orderSize;
            OrderWeight = orderWeight;
            CustomerName = customerName;
            CustomerAddress = customerAddress;
            CustomerEmail = customerEmail;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "orderID")]
        public int? OrderID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "orderSize")]
        public int? OrderSize { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "orderWeight")]
        public int? OrderWeight { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "customerName")]
        public string CustomerName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "customerAddress")]
        public string CustomerAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "customerEmail")]
        public string CustomerEmail { get; set; }
    }
}
