// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace WebApplication2.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ShipmentState
    {
        /// <summary>
        /// Initializes a new instance of the ShipmentState class.
        /// </summary>
        public ShipmentState() { }

        /// <summary>
        /// Initializes a new instance of the ShipmentState class.
        /// </summary>
        public ShipmentState(int? orderID = default(int?), string status = default(string))
        {
            OrderID = orderID;
            Status = status;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "orderID")]
        public int? OrderID { get; set; }

        /// <summary>
        /// Possible values include: 'PENDING', 'SHIPPED', 'DELIVERED'
        /// </summary>
        [JsonProperty(PropertyName = "state")]
        public string Status { get; set; }

    }
}
